# Generated by Django 4.2.6 on 2023-11-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('product_information_60', models.CharField(max_length=60, verbose_name='Информация о товаре(Кратко)')),
                ('product_information', models.TextField(verbose_name='Информация о товаре')),
                ('keyboard_type', models.CharField(max_length=50, verbose_name='Тип клавиатуры')),
                ('connection', models.CharField(max_length=50, verbose_name='Подключение')),
                ('backlit_keys', models.CharField(max_length=50, verbose_name='Подсветка клавиш')),
                ('form', models.CharField(max_length=50, verbose_name='Форма')),
                ('peculiarities', models.TextField(verbose_name='Особенности')),
                ('manufacturer_country', models.CharField(max_length=50, verbose_name='Страна-производитель')),
                ('layout', models.CharField(max_length=50, verbose_name='Раскладка')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('interface', models.CharField(max_length=50, verbose_name='Интерфейс')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('frame', models.CharField(max_length=50, verbose_name='Корпус')),
                ('additional_functions', models.TextField(verbose_name='Дополнительные функции')),
                ('sensing_distance', models.CharField(max_length=50, verbose_name='Дистанция срабатывания')),
                ('pressure_force', models.CharField(max_length=50, verbose_name='Сила нажатия')),
                ('production_technology', models.CharField(max_length=50, verbose_name='Технология производства')),
                ('number_of_keyboard_buttons', models.IntegerField(verbose_name='Количество кнопок клавиатуры')),
                ('key_features', models.CharField(max_length=100, verbose_name='Особенности клавиш')),
                ('equipment', models.TextField(verbose_name='Комплектация')),
                ('dimensions', models.CharField(max_length=50, verbose_name='Размеры')),
                ('keystroke_resource', models.CharField(max_length=50, verbose_name='Ресурс нажатия клавиш')),
                ('color_of_cyrillic_letters', models.CharField(max_length=50, verbose_name='Цвет букв кириллицы')),
                ('os_compatibility', models.CharField(max_length=100, verbose_name='Совместимость с ОС')),
                ('cable_length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длина кабеля, м')),
                ('brand_registration_country', models.CharField(max_length=50, verbose_name='Страна регистрации бренда')),
                ('guarantee', models.CharField(max_length=50, verbose_name='Гарантия')),
                ('imageURL_title', models.URLField(verbose_name='Титульное Изображение (URL)')),
                ('imageURL_1', models.URLField(verbose_name='Изображение 1(URL)')),
                ('imageURL_2', models.URLField(verbose_name='Изображение 2(URL)')),
                ('imageURL_3', models.URLField(verbose_name='Изображение 3(URL)')),
            ],
            options={
                'verbose_name': 'Пост с товаром',
                'verbose_name_plural': 'Посты с товаром',
            },
        ),
    ]
