# Generated by Django 4.2.6 on 2023-11-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
    ]
